### ISSUE TITLE
Time/Date is Displayed Wrong

### ISSUE THREAD

**Issue by LunarVigilante** [iTzArshia/GPT-Discord-Bot#13]
When asked for today's date, the bot asked for what timezone (Which is normal) but then posted the exact message:

"In Pacific Daylight Time (PDT), today's date is: {{moment().tz('America/Los_Angeles').format('dddd, MMMM Do YYYY')}}."

Showing the code for the time rather than properly formatting

**Comment by iTzArshia** [comment]
That's not my fault! It's OpenAI engine, my bot is just an example bot for using OpenAI models.
