### ISSUE TITLE
TypeError: openAI.Configuration is not a constructor

### ISSUE THREAD

**Issue by MaelHan** [iTzArshia/GPT-Discord-Bot#14]
Hello, i just got this error **" TypeError: openAI.Configuration is not a constructor "** when i use the command **!ask** [MY MESSAGE]

I don't know how to fix this problem, someone told me about changing the code but i don't what to change.

Thanks in advance.

**Comment by iTzArshia** [comment]
That's why you are using latest version of OpenAI library for OLD Code download & use this one its fix with new version

https://github.com/iTzArshia/GPT-Discord-Bot/releases/tag/v3.0.0

Also don't forget to ⭐ the repo <3
