### ISSUE TITLE
Feature request: Configurable API source so we can use other APIs such as BLOOM or BERT.

### ISSUE THREAD

**Issue by DarkIlluminatus** [iTzArshia/GPT-Discord-Bot#2]
Or any of the BigScience models. That way we can choose to use open source LLM training data and use it to generate GAN and RNN content through the chat history for live fine tuning.

**Comment by iTzArshia** [comment]
Can you explain more? 🤔 
You mean create a command which you can select engine and settings such as top_p and... ?

**Comment by DarkIlluminatus** [comment]
Oh sorry, I didn't mean to take so long. Just some way by command or configuration in the code to have the option change to another API that isn't openAI's. Somewhere we can manually set the API URL and Key in some way to utilized other LLM libraries.

**Comment by iTzArshia** [comment]
Well as my source works with OpenAI's official library it's not possible to do it.
Also using different APIs need different codes we can't just change the API URL and expect it to work

**Comment by DarkIlluminatus** [comment]
Yeah, I'm aware of the other changes to commands and whatnot, as will I
suspect, most people who would want to use it for a different API. I've
learned quite a bit more about discord bot code since then though, so if
you don't believe you'll be able to do it I understand and can just add it
on my local copy. Just thought the feature would draw more users for ya and
increase functionality of the bot (for users who can implement the API
specific commands themselves) to include the ability to choose open source
options for which LLM API we can use.

**Comment by iTzArshia** [comment]
Well I told you its not possible 👀

**Comment by DarkIlluminatus** [comment]
It's definitely possible, but I understand if you think you can't do it.
